
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test
